[HYDRATOR-1073] Adding Fail pipeline sink
hydrator/failpipeline-sink pull request #1
Opened 2017-01-09 13:52 UTC by romy-khetan

2017-01-11 00:17 UTC, russorat commented on failpipeline-sink-plugins.iml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should not be checked in. Please add a .gitignore to this repo. a good one can be found here: https://github.com/hydrator/example-transform/blob/master/.gitignore

2017-01-11 00:18 UTC, russorat commented on pom.xml
> +      <version>1.6</version>
please use a property for the version similar to the other dependencies.

2017-01-11 00:18 UTC, russorat commented on pom.xml
> +  <dependencies>
Seems like an large number of dependencies for such a simple plugin. are you sure all of them are needed?

2017-01-11 01:53 UTC, abhinavbansal246 requested changes

2017-01-11 01:53 UTC, abhinavbansal246 commented on LICENSE.txt
> +Copyright © 2014-2015 Cask Data, Inc.
update the copyright 2017

2017-01-11 01:53 UTC, abhinavbansal246 commented on README.rst
> +=======================
Length not matching the text

2017-01-11 01:53 UTC, abhinavbansal246 commented on src/main/java/co/cask/hydrator/plugin/batch/sink/FailPipelineSink.java
> +public class FailPipelineSink extends BatchSink<StructuredRecord, Void, Void> {
extend the reference batch Sink instead of the batch sink, That way we will have a config property of plugin reference batch name.

2017-01-11 01:54 UTC, abhinavbansal246 commented
Please add the FailSink doc file providing the basic info about the plugin.

2017-01-12 11:32 UTC, romy-khetan commented
@russorat @abhinavbansal246 
I have updated the PR. Please review.

2017-01-12 22:31 UTC, russorat commented on pom.xml
> +  <version>1.6.0-SNAPSHOT</version>
no SNAPSHOT in master

2017-01-12 22:31 UTC, russorat commented on pom.xml
> +    <cdap.version>4.1.0-SNAPSHOT</cdap.version>
no SNAPSHOT in master

2017-01-12 22:32 UTC, russorat commented on pom.xml
> +    <app.parents>system:cdap-etl-batch[4.1.0-SNAPSHOT,4.2.0-SNAPSHOT),system:cdap-etl-realtime[4.1.0-SNAPSHOT,4.2.0-SNAPSHOT),system:cdap-data-pipeline[4.1.0-SNAPSHOT,4.2.0-SNAPSHOT)</app.parents>
this is probably valid since 4.0.0. 4.1.0-SNAPSHOT -> 4.0.0

2017-01-12 22:33 UTC, russorat commented on src/main/java/co/cask/hydrator/plugin/batch/sink/FailPipelineSink.java
> + * Copyright © 2016 Cask Data, Inc.
2017

2017-01-12 22:33 UTC, russorat commented on src/main/java/co/cask/hydrator/plugin/batch/sink/FailPipelineSink.java
> +@Plugin(type = "batchsink")
"batchsink" -> Plugin.BATCH_SINK or something like that

2017-01-12 22:34 UTC, russorat commented on src/test/java/co/cask/hydrator/plugin/batch/sink/FailPipelineSinkTest.java
> + * Copyright © 2016 Cask Data, Inc.
17

2017-01-12 22:34 UTC, russorat commented on src/test/java/co/cask/hydrator/plugin/batch/sink/FailPipelineSinkTest.java
> +  protected static final ArtifactSummary DATAPIPELINE_ARTIFACT = new ArtifactSummary("data-pipeline", "3.2.0");
should this be 4.0.0?

2017-01-13 00:49 UTC, abhinavbansal246 commented on src/main/java/co/cask/hydrator/plugin/batch/sink/FailPipelineSink.java
> +@Plugin(type = "batchsink")
BatchSink.pluginType

2017-01-13 00:51 UTC, abhinavbansal246 commented on pom.xml
> +  <version>1.6.0-SNAPSHOT</version>
@russorat The way we were going to handle this was that one PR will merge code from develop to master and another one will bump the version. We can also do the version bumping from github web ui

2017-01-13 01:17 UTC, russorat commented on pom.xml
> +  <version>1.6.0-SNAPSHOT</version>
ok

2017-01-13 03:20 UTC, russorat commented
small changes, otherwise LGTM

2017-01-13 09:01 UTC, romy-khetan commented
@russorat @abhinavbansal246 
I have made the required changes, please review.

2017-01-16 23:13 UTC, russorat commented
@romy-khetan can you address @abhinavbansal246 's comments?

2017-01-17 05:37 UTC, romy-khetan commented
@russorat I have already addressed @abhinavbansal246 's comments. Please see the links below for the references:
https://github.com/hydrator/failpipeline-sink/pull/1/commits/c9c671b76d3822de2aa3c50428accd9130066df1
https://github.com/hydrator/failpipeline-sink/blob/develop/docs/FailPipeline-batchsink.md
Or, Could you please provide me the comments references which are missed in the above links?

2017-01-18 05:59 UTC, abhinavbansal246 approved these changes

2017-01-18 05:59 UTC, abhinavbansal246 commented
LGTM

2017-01-18 15:06 UTC, merged